Ethernet Settings:
  Input:
    IP: 239.255.76.67
    Port: 7667
    Interface: 169.254.239.175
  Output:
    IP: 239.255.54.98
    Port: 6790
    Interface: 169.254.239.175
Zones:
  # Note: vertex values, z range values, and hysteresis values are always in meters.
  Zone A:
    Vertices: [[-2.25, -3], [0.5, -3], [0.5, 3], [-2.25, 3]]
    Z Range: [0, 5]
    Hysteresis: 0.15
  Zone B:
    Vertices: [[-0.5, -3], [2.25, -3], [2.25, 3], [-0.5, 3]]
    Z Range: [0, 5]
    Hysteresis: 0.15
Output Interval: 10 # Can be an integer or float. Optional, default = 10.0
Print Output: True  # Optional, default = True